/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AntrenorlerRouteImport } from './routes/antrenorler'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as IletisimRouteImport } from './routes/iletisim'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AntrenorlerRoute = AntrenorlerRouteImport.update({
  id: '/antrenorler',
  path: '/antrenorler',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/antrenorler': typeof AntrenorlerRoute
  '/galeri': typeof GaleriRoute
  '/iletisim': typeof IletisimRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/antrenorler': typeof AntrenorlerRoute
  '/galeri': typeof GaleriRoute
  '/iletisim': typeof IletisimRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/antrenorler': typeof AntrenorlerRoute
  '/galeri': typeof GaleriRoute
  '/iletisim': typeof IletisimRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/antrenorler' | '/galeri' | '/iletisim'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/antrenorler' | '/galeri' | '/iletisim'
  id: '__root__' | '/' | '/antrenorler' | '/galeri' | '/iletisim'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AntrenorlerRoute: typeof AntrenorlerRoute
  GaleriRoute: typeof GaleriRoute
  IletisimRoute: typeof IletisimRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antrenorler': {
      id: '/antrenorler'
      path: '/antrenorler'
      fullPath: '/antrenorler'
      preLoaderRoute: typeof AntrenorlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AntrenorlerRoute: AntrenorlerRoute,
  GaleriRoute: GaleriRoute,
  IletisimRoute: IletisimRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
